# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_prof',
            name='phone_num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user_prof',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
