# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0002_auto_20180605_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_prof',
            name='phone_num',
            field=models.IntegerField(null=True),
        ),
    ]
