# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0003_auto_20180605_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_prof',
            name='user_location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='watch.Neighborhood'),
        ),
    ]
