# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-06 05:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watch', '0004_auto_20180605_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='bussiness',
            name='image',
            field=models.ImageField(blank=True, upload_to='business_images'),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=models.ImageField(blank=True, upload_to='neighborhood_images'),
        ),
        migrations.AddField(
            model_name='user_prof',
            name='image',
            field=models.ImageField(blank=True, upload_to='user_images'),
        ),
    ]
